import Head from 'next/head'
import { useEffect, useState } from 'react'

import { fetchPosts, createPost, reset } from "../store/post/postSlice"

import { useDispatch, useSelector } from "react-redux"
import { toast } from "react-toastify"
import { Oval } from  'react-loader-spinner'
import { useRouter } from "next/router";


const Dashboard = ({ data:walletData, connectWallet }) => {

    const dispatch = useDispatch()

    const [data, setData] = useState({
        title:"",
        description:"",
    })



    useEffect(() => {
        dispatch(fetchPosts())
    },[])

    const { posts, isLoading, isUploading, isSuccess, isError, message } = useSelector((state) => state.post)
    const { user } = useSelector((state) => state.auth)
    const router = useRouter();

    useEffect(() => {
        if(!user){
            router.push("/login")
        }
    },[user])

    useEffect(() => {
        if(isUploading){
            setData({
                title:"",
                description:""
            })
        }
        if(isSuccess){
            toast.success("Uploaded on blockchain")
            connectWallet()
            dispatch(reset())
        }
    },[isUploading, isSuccess])

    const addPost = () => {
        console.log(data.title)
        console.log(data.description)

        if(!data.title || ! data.description){
            return toast.error("Please enter all fields")
        }

        if(data.title.trim().length<3){
            return toast.error("Title is too short")
        }

        if(data.description.length<10 && data.description.trim().length<5){
            return toast.error("Description is too short")
        }

        const postData = {
            id: Math.floor((Math.random() * 1000000) + 1),
            post_address: walletData.address,
            name: user.name,
            title: data.title,
            description: data.description,
        }

        console.log(postData)

        dispatch(createPost(postData))

    }

    const showPosts = posts.map(onePost => (
        <div className='post my-4 w-auto m-auto rounded pb-0.5'>
            <div className='flex justify-start items-center'>
                <img 
                    src="https://thumbs.dreamstime.com/b/cryptocurrency-icon-vector-bitcoin-blockchain-male-person-profile-avatar-digital-wallet-glyph-pictogram-illustration-210078657.jpg"
                    alt="" 
                    className='w-10 rounded-full mx-3 mt-3'
                />
                <p className='mt-3'>{onePost.name}</p>
                <p className='mt-3 mx-5 p-2 bg-orange-600 rounded text-zinc-600'>
                    {`${onePost.post_address.substr(0,6)}....${onePost.post_address.substr(-4)}`}
                </p>
            </div>
            <div className='m-auto px-2 py-1'>
                <p
                    className='p-2 rounded w-full'
                >{onePost.title}</p>
            </div>
            <div className='m-auto px-2'>
                <p
                    placeholder='Description'
                    className='w-full p-2 rounded bg-zinc-800'
                >{onePost.description}</p>
            </div>
            <div className='m-auto px-2 mb-2'>
            <p
                className='p-1 text-blue-400 rounded w-full cursor-pointer'
                >Like/Tip</p>
            </div>
        </div>
    ))

    if(!user){
        return <div></div>
    }

  return (
    <div>
        <Head>
            <title>Dashboard</title>
            <meta name="description" content="Generated by create next app" />
            {/* <link rel="icon" href="/favicon.ico" /> */}
        </Head>
        <nav className="lgnav bg-slate-800 px-4 py-2 sticky top-0 bottom-0 h-14 w-auto">
            <ul className="flex justify-end">
            <li className="mx-2">
                <button 
                    className='py-1 px-3 rounded bg-orange-500 hover:bg-orange-400 text-lg'
                    // onClick={getContract}
                >
                    {walletData?walletData.address?`${walletData.address.substr(0,6)}....${walletData.address.substr(-4)}`:"Connect Wallet": "Connect Wallet"}
                    {/* Connect Wallet */}
                </button>
            </li>
            <li className="mx-2">
                <button className='py-1 px-3 rounded bg-blue-500 hover:bg-blue-400 text-lg'>
                    {walletData?String(walletData.balance).slice(0,7):0} Ether
                    {/* Ether */}
                </button>
            </li>
            </ul>
        </nav>

        <div className='continer flex justify-center w-11/12 m-auto gap-12 mt-1'>
            {/* div 1 */}
            <div className='w-1/4 mt-1 h-1 sticky top-16'> {/*  sticky */}
                {/* profile */}
                <div className='w-11/12 m-auto'>
                    <div className='h-24 bg-orange-400 cursor-pointer rounded'>
                        {/* Top<p>Here</p> */}
                    </div>
                    <div className='mb-2'>
                    <img 
                        src="https://thumbs.dreamstime.com/b/cryptocurrency-icon-vector-bitcoin-blockchain-male-person-profile-avatar-digital-wallet-glyph-pictogram-illustration-210078657.jpg" 
                        alt=""
                        className='w-1/3 m-auto rounded-full -mt-10 mb-2'
                        // style={{top:"-20%"}}
                    />
                        <div className='text-center'>
                            <p className='text-lg font-semibold'>{user.name}</p>
                            <p>This is bio</p>
                            <p>This is bio</p>
                        </div>
                    </div>
                    {/* <hr/> */}
                    <div className='rounded m-1 p-2' style={{backgroundColor: "#303338"}}> {/* #3E4042 */}
                        <p className='text-center mb-1 text-lg font-semibold'>Notifications</p>
                        <div className='h-36 overflow-y-auto notilist'>
                            <div className='text-center p-2 w-11/12 m-auto rounded cursor-pointer my-2 notification hover:scale-105'>
                                John Doe added a post.
                            </div>
                            <div className='text-center p-2 w-11/12 m-auto rounded cursor-pointer my-2 notification hover:scale-105'>
                                John Doe added a post.
                            </div>
                            <div className='text-center p-2 w-11/12 m-auto rounded cursor-pointer my-2 notification hover:scale-105'>
                                John Doe added a post.
                            </div>
                            
                            <div className='text-center p-2 w-11/12 m-auto rounded cursor-pointer my-2 notification hover:scale-105'>
                                John Doe added a post.
                            </div>
                        </div>
                    </div>

                    <div className='bg-zinc-700 hover:bg-zinc-600 p-2 rounded m-1 cursor-pointer hover:scale-105'>
                            <img
                                src="https://pngimg.com/uploads/hacker/hacker_PNG24.png"
                                alt=""
                                className='w-2/4 rounded m-auto'
                            />
                            <p className='text-center text-gray-400 font-medium text-base'>Feel As Anonymous</p>
                            <p className='text-center text-gray-400 font-medium text-base'>Right To Privacy</p>
                    </div>

                </div>
            </div>
            {/* div 2 */}
            <div className='w-1/2 mt-1'>
                <div className='createpost w-auto bg-slate-600 m-auto rounded pb-0.5 hover:scale-105'>
                    <div className='flex justify-start items-center'>
                        <img 
                            src="https://thumbs.dreamstime.com/b/cryptocurrency-icon-vector-bitcoin-blockchain-male-person-profile-avatar-digital-wallet-glyph-pictogram-illustration-210078657.jpg"
                            alt="" 
                            className='w-10 rounded-full mx-3 mt-3'
                        />
                        <p className='mt-3'>{user.name}</p>
                        {isUploading?(
                            <p className='mt-3 mx-5 p-2 bg-green-500 rounded text-zinc-600'>Uploading...</p>
                        ):(
                            <p className='mt-3 mx-5 p-2 bg-orange-400 rounded text-zinc-600'>Create a post on blockchain</p>
                        )}
                    </div>
                    <div className='m-auto p-2'>
                        <input 
                            type="text" 
                            placeholder='Title'
                            className='hover:bg-zinc-700 p-2 rounded w-full focus:border-sky-500 focus:ring-sky-500 focus:ring-1 focus:outline-none'
                            value={data.title}
                            onChange={(e) => setData({
                                ...data,
                                title: e.target.value
                            })}
                        />
                    </div>
                    <div className='m-auto px-2'>
                        <textarea
                            placeholder='Description'
                            className='hover:bg-zinc-700 w-full h-16 p-2 rounded focus:border-sky-500 focus:ring-sky-500 focus:ring-1 focus:outline-none'
                            value={data.description}
                            onChange={(e) => setData({
                                ...data,
                                description: e.target.value
                            })}
                        />
                    </div>
                    <div className='flex justify-center px-2 py-1'>
                        <button
                            className='bg-green-600 hover:bg-green-500 px-4 py-2 rounded font-semibold text-white hover:scale-105'
                            onClick={addPost}
                        >Create Post</button>
                    </div>
                </div>


                {/* posts */}
                {!isLoading?showPosts:(
                    <div style={{paddingTop:"20%"}}>
                        <Oval
                            heigth="500"
                            width="500"
                            color='grey'
                            ariaLabel='loading'
                        />
                    </div>
                )}

            </div>
            {/* div 3 */}
            <div className='w-1/4 h-1 sticky top-16'>
                <div className=''> {/*  flex h-screen */}
                    {/* profile */}
                    <div className='w-11/12 m-auto'>
                        <div className='bg-slate-500 p-2 rounded mx-2 hover:bg-slate-400 cursor-pointer hover:scale-105'>
                            <img
                                src="https://cdn-icons-png.flaticon.com/512/2091/2091665.png"
                                alt=""
                                className='w-1/3 rounded m-auto'
                            />
                            <p className='text-center text-black font-medium text-base m-2'>Connect with different people in decentralised app.</p>
                        </div>

                        <div className='bg-orange-300 hover:bg-orange-200 p-2 rounded m-2 cursor-pointer hover:scale-105'>
                            <img
                                src="https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/metamask-icon.png"
                                alt=""
                                className='w-1/3 rounded m-auto'
                            />
                            <p className='text-center text-orange-900 font-medium text-base m-2'>Decentralised Wallets.</p>
                        </div>


                        <div className='bg-gray-400 hover:bg-gray-300 p-2 rounded m-2 cursor-pointer hover:scale-105'>
                            <img
                                src="https://cryptologos.cc/logos/ethereum-eth-logo.png"
                                alt=""
                                className='w-1/3 rounded m-auto'
                            />
                            <p className='text-center text-gray-700 font-medium text-base m-2'>Build on etherium blockchian.</p>
                        </div>

                        <div className='bg-slate-200 hover:bg-slate-100 p-2 rounded m-2 cursor-pointer hover:scale-105'>
                            <img
                                src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/NFT_Icon.png/640px-NFT_Icon.png"
                                alt=""
                                className='w-1/3 rounded m-auto'
                            />
                            <p className='text-center text-gray-700 font-medium text-base m-2'>NFTs</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  )
}

export default Dashboard