import Head from 'next/head'
import { useState, useEffect } from 'react'
// import { connect } from "../etherjs/walletWrapper"
import { register, login, reset, logout } from "../store/auth/authSlice";
import { useDispatch, useSelector } from "react-redux";
import { toast } from "react-toastify";
import { useRouter } from "next/router";


const Login = ({data, connectWallet}) => {
    const [uname, setUname] = useState('')

    const dispatch = useDispatch()
    const router = useRouter();

    const { user, isSuccess, isError, message } = useSelector((state) => state.auth)


    useEffect(() => {
        if(message){
            toast.warning(message)
            // dispatch(reset());
        }
        if(user){
            // route to dashboard
            router.push("/dashboard");
        }
        // dispatch(reset());
    },[message, user])


    const signUp = () => {
        //sign up here
        console.log(uname)
        if(!data){
            return toast.error("Connect wallet to sign up")
        }
        if(!data.address){
            return toast.error("Connect wallet to sign up")
        }
        if(uname.length < 3){
            return toast.error("Name must contain at least 3 characters.")
        }
        const newUser = {
            name: uname,
            address: data.address
        }
        dispatch(register(newUser))
    }

  return (
    <div className="main">
        <Head>
            <title>Login</title>
            <meta name="description" content="Generated by create next app" />
            {/* <link rel="icon" href="/favicon.ico" /> */}
        </Head>
      <nav className="lgnav bg-slate-800 px-4 py-4">
        <ul className="flex justify-end">
          <li className="mx-2">
            <button 
                className='py-2 px-3 rounded bg-orange-500 hover:bg-orange-400 text-lg'
                onClick={connectWallet}
            >
                {data?data.address?`${data.address.substr(0,6)}....${data.address.substr(-4)}`:"Connect Wallet": "Connect Wallet"}
            </button>
          </li>
          <li className="mx-2">
            <button className='py-2 px-3 rounded bg-blue-500 hover:bg-blue-400 text-lg'>{data?String(data.balance).slice(0,5):0} Ether</button>
          </li>
        </ul>
      </nav>
        <div className="lgform rounded relative top-32 w-96 h-72 m-auto flex justify-center  form">
            <div>
                <center>
                    <img 
                        src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/MetaMask_Fox.svg/800px-MetaMask_Fox.svg.png" 
                        alt=""
                        className='w-20 mt-4'
                    />
                </center>
                <h1 className='mb-7 text-center text-3xl'>Create an account</h1>
                <input
                    type="text"
                    placeholder="Name"
                    className='p-2 rounded w-80	focus:border-sky-500 focus:ring-sky-500 focus:ring-1 focus:outline-none'
                    onChange={(e) => {
                        setUname(e.target.value)
                    }}
                    value={uname}
                />
                <br/>
                <center>
                    <button 
                        className='my-5 py-2 px-3 rounded bg-violet-600 hover:bg-violet-500 text-lg'
                        onClick={signUp}
                    >Sign Up</button>
                </center>
            </div>
        </div>
    </div>
  )
}

export default Login